# nginx proxy address - http://172.17.0.1:8989

name: arrstack
x-logging: &default-logging
  options:
    max-size: '5m'
    max-file: '1'
  driver: json-file

services:
  sonarr:
    image: ghcr.io/hotio/sonarr:latest
    container_name: arrstack-sonarr
    hostname: ${BASE_HOST_NAME:-$HOSTNAME}
    restart: always
    pull_policy: always
    logging: *default-logging
    environment:
      TZ: ${TZ:-America/New_York}
      CONTAINER_NAME: arrstack-sonarr
      HOSTNAME: ${BASE_HOST_NAME:-$HOSTNAME}
      PUID: ${SERVICE_USER:-1000}
      PGID: ${SERVICE_GROUP:-1000}
      UMASK: 022
    ports:
      - '172.17.0.1:8989:8989'
    volumes:
      - './volumes/config/sonarr:/config'
      - './volumes/data/media/tv:/data/tv'
      - './volumes/data/downloads:/data/downloads'
    labels:
      - 'traefik.enable=true'
      - 'cloudflare.enable=true'
      - 'traefik.docker.network=proxy'
      - 'cloudflare.service=http://arrstack-sonarr:8989'
      - 'cloudflare.hostname=arrstack.${CLOUDFLARE_ZONE_NAME:-}'
      - 'traefik.http.routers.arrstack-sonarr.entrypoints=http'
      - 'traefik.http.routers.arrstack-sonarr-secure.tls=true'
      - 'traefik.http.routers.arrstack-sonarr.rule=Host($(${BASE_HOST_NAME:-$HOSTNAME}))'
      - 'traefik.http.middlewares.arrstack-sonarr-https-redirect.redirectscheme.scheme=https'
      - 'traefik.http.routers.arrstack-sonarr.middlewares=arrstack-sonarr-https-redirect'
      - 'traefik.http.routers.arrstack-sonarr-secure.entrypoints=https'
      - 'traefik.http.routers.arrstack-sonarr-secure.rule=Host($(${BASE_HOST_NAME:-$HOSTNAME}))'
      - 'traefik.http.routers.arrstack-sonarr-secure.tls.certresolver=cloudflare'
      - 'traefik.http.routers.arrstack-sonarr-secure.service=arrstack-sonarr'
      - 'traefik.http.services.arrstack-sonarr.loadbalancer.server.port=8989'
    networks:
      - arrstack
      - proxy
      - cloudflare

  # Radarr: A fork of Sonarr to work with movies. Automatically monitors and downloads movies, handles quality upgrades, and manages your movie collection with an elegant web interface.
  radarr:
    image: ghcr.io/hotio/radarr:latest
    container_name: arrstack-radarr
    hostname: ${BASE_HOST_NAME:-$HOSTNAME}
    restart: always
    pull_policy: always
    logging: *default-logging
    environment:
      TZ: ${TZ:-America/New_York}
      CONTAINER_NAME: arrstack-radarr
      HOSTNAME: ${BASE_HOST_NAME:-$HOSTNAME}
      PUID: ${SERVICE_USER:-1000}
      PGID: ${SERVICE_GROUP:-1000}
      UMASK: 022
    ports:
      - '172.17.0.1:7878:7878'
    volumes:
      - './volumes/config/radarr:/config'
      - './volumes/data/media/movies:/data/movies'
      - './volumes/data/downloads:/data/downloads'
    labels:
      - 'traefik.enable=true'
      - 'cloudflare.enable=true'
      - 'traefik.docker.network=proxy'
      - 'cloudflare.service=http://arrstack-radarr:7878'
      - 'cloudflare.hostname=arrstack.${CLOUDFLARE_ZONE_NAME:-}'
      - 'traefik.http.routers.arrstack-radarr.entrypoints=http'
      - 'traefik.http.routers.arrstack-radarr-secure.tls=true'
      - 'traefik.http.routers.arrstack-radarr.rule=Host($(${BASE_HOST_NAME:-$HOSTNAME}))'
      - 'traefik.http.middlewares.arrstack-radarr-https-redirect.redirectscheme.scheme=https'
      - 'traefik.http.routers.arrstack-radarr.middlewares=arrstack-radarr-https-redirect'
      - 'traefik.http.routers.arrstack-radarr-secure.entrypoints=https'
      - 'traefik.http.routers.arrstack-radarr-secure.rule=Host($(${BASE_HOST_NAME:-$HOSTNAME}))'
      - 'traefik.http.routers.arrstack-radarr-secure.tls.certresolver=cloudflare'
      - 'traefik.http.routers.arrstack-radarr-secure.service=arrstack-radarr'
      - 'traefik.http.services.arrstack-radarr.loadbalancer.server.port=7878'
    networks:
      - arrstack
      - proxy
      - cloudflare

  # Lidarr: A music collection manager for Usenet and BitTorrent users. It can monitor multiple RSS feeds for new albums from your favorite artists and will interface with clients and indexers to grab, sort, and rename them.
  lidarr:
    image: ghcr.io/hotio/lidarr:latest
    container_name: arrstack-lidarr
    hostname: ${BASE_HOST_NAME:-$HOSTNAME}
    restart: always
    pull_policy: always
    logging: *default-logging
    environment:
      TZ: ${TZ:-America/New_York}
      CONTAINER_NAME: arrstack-lidarr
      HOSTNAME: ${BASE_HOST_NAME:-$HOSTNAME}
      PUID: ${SERVICE_USER:-1000}
      PGID: ${SERVICE_GROUP:-1000}
      UMASK: 022
    ports:
      - '172.17.0.1:8686:8686'
    volumes:
      - './volumes/config/lidarr:/config'
      - './volumes/data/media/music:/data/music'
      - './volumes/data/downloads:/data/downloads'
    labels:
      - 'traefik.enable=true'
      - 'cloudflare.enable=true'
      - 'traefik.docker.network=proxy'
      - 'cloudflare.service=http://arrstack-lidarr:8686'
      - 'cloudflare.hostname=arrstack.${CLOUDFLARE_ZONE_NAME:-}'
      - 'traefik.http.routers.arrstack-lidarr.entrypoints=http'
      - 'traefik.http.routers.arrstack-lidarr-secure.tls=true'
      - 'traefik.http.routers.arrstack-lidarr.rule=Host($(${BASE_HOST_NAME:-$HOSTNAME}))'
      - 'traefik.http.middlewares.arrstack-lidarr-https-redirect.redirectscheme.scheme=https'
      - 'traefik.http.routers.arrstack-lidarr.middlewares=arrstack-lidarr-https-redirect'
      - 'traefik.http.routers.arrstack-lidarr-secure.entrypoints=https'
      - 'traefik.http.routers.arrstack-lidarr-secure.rule=Host($(${BASE_HOST_NAME:-$HOSTNAME}))'
      - 'traefik.http.routers.arrstack-lidarr-secure.tls.certresolver=cloudflare'
      - 'traefik.http.routers.arrstack-lidarr-secure.service=arrstack-lidarr'
      - 'traefik.http.services.arrstack-lidarr.loadbalancer.server.port=8686'
    networks:
      - arrstack
      - proxy
      - cloudflare

  # Readarr: Book collection manager for Usenet and BitTorrent users. It integrates with clients such as SABnzbd, NZBGet, QBittorrent, and Deluge.
  readarr:
    image: ghcr.io/hotio/readarr:latest
    container_name: arrstack-readarr
    hostname: ${BASE_HOST_NAME:-$HOSTNAME}
    restart: always
    pull_policy: always
    logging: *default-logging
    environment:
      TZ: ${TZ:-America/New_York}
      CONTAINER_NAME: arrstack-readarr
      HOSTNAME: ${BASE_HOST_NAME:-$HOSTNAME}
      PUID: ${SERVICE_USER:-1000}
      PGID: ${SERVICE_GROUP:-1000}
      UMASK: 022
    ports:
      - '172.17.0.1:8787:8787'
    volumes:
      - './volumes/config/readarr:/config'
      - './volumes/data/media/books:/data/books'
      - './volumes/data/downloads:/data/downloads'
    labels:
      - 'traefik.enable=true'
      - 'cloudflare.enable=true'
      - 'traefik.docker.network=proxy'
      - 'cloudflare.service=http://arrstack-readarr:8787'
      - 'cloudflare.hostname=arrstack.${CLOUDFLARE_ZONE_NAME:-}'
      - 'traefik.http.routers.arrstack-readarr.entrypoints=http'
      - 'traefik.http.routers.arrstack-readarr-secure.tls=true'
      - 'traefik.http.routers.arrstack-readarr.rule=Host($(${BASE_HOST_NAME:-$HOSTNAME}))'
      - 'traefik.http.middlewares.arrstack-readarr-https-redirect.redirectscheme.scheme=https'
      - 'traefik.http.routers.arrstack-readarr.middlewares=arrstack-readarr-https-redirect'
      - 'traefik.http.routers.arrstack-readarr-secure.entrypoints=https'
      - 'traefik.http.routers.arrstack-readarr-secure.rule=Host($(${BASE_HOST_NAME:-$HOSTNAME}))'
      - 'traefik.http.routers.arrstack-readarr-secure.tls.certresolver=cloudflare'
      - 'traefik.http.routers.arrstack-readarr-secure.service=arrstack-readarr'
      - 'traefik.http.services.arrstack-readarr.loadbalancer.server.port=8787'
    networks:
      - arrstack
      - proxy
      - cloudflare

  # Prowlarr: A powerful indexer manager/proxy built on the arr stack. Seamlessly integrates with Sonarr, Radarr, Lidarr, and Readarr, supporting both Torrent Trackers and Usenet Indexers with centralized management.
  prowlarr:
    image: ghcr.io/hotio/prowlarr:latest
    container_name: arrstack-prowlarr
    hostname: ${BASE_HOST_NAME:-$HOSTNAME}
    restart: always
    pull_policy: always
    logging: *default-logging
    environment:
      TZ: ${TZ:-America/New_York}
      CONTAINER_NAME: arrstack-prowlarr
      HOSTNAME: ${BASE_HOST_NAME:-$HOSTNAME}
      PUID: ${SERVICE_USER:-1000}
      PGID: ${SERVICE_GROUP:-1000}
      UMASK: 022
    ports:
      - '172.17.0.1:9696:9696'
    volumes:
      - './volumes/config/prowlarr:/config'
    labels:
      - 'traefik.enable=true'
      - 'cloudflare.enable=true'
      - 'traefik.docker.network=proxy'
      - 'cloudflare.service=http://arrstack-prowlarr:9696'
      - 'cloudflare.hostname=arrstack.${CLOUDFLARE_ZONE_NAME:-}'
      - 'traefik.http.routers.arrstack-prowlarr.entrypoints=http'
      - 'traefik.http.routers.arrstack-prowlarr-secure.tls=true'
      - 'traefik.http.routers.arrstack-prowlarr.rule=Host($(${BASE_HOST_NAME:-$HOSTNAME}))'
      - 'traefik.http.middlewares.arrstack-prowlarr-https-redirect.redirectscheme.scheme=https'
      - 'traefik.http.routers.arrstack-prowlarr.middlewares=arrstack-prowlarr-https-redirect'
      - 'traefik.http.routers.arrstack-prowlarr-secure.entrypoints=https'
      - 'traefik.http.routers.arrstack-prowlarr-secure.rule=Host($(${BASE_HOST_NAME:-$HOSTNAME}))'
      - 'traefik.http.routers.arrstack-prowlarr-secure.tls.certresolver=cloudflare'
      - 'traefik.http.routers.arrstack-prowlarr-secure.service=arrstack-prowlarr'
      - 'traefik.http.services.arrstack-prowlarr.loadbalancer.server.port=9696'
    networks:
      - arrstack
      - proxy
      - cloudflare

  # Whisparr: An adult movie collection manager for Usenet and BitTorrent users.
  whisparr:
    image: ghcr.io/hotio/whisparr:latest
    container_name: arrstack-whisparr
    hostname: ${BASE_HOST_NAME:-$HOSTNAME}
    restart: always
    pull_policy: always
    logging: *default-logging
    environment:
      TZ: ${TZ:-America/New_York}
      CONTAINER_NAME: arrstack-whisparr
      HOSTNAME: ${BASE_HOST_NAME:-$HOSTNAME}
      PUID: ${SERVICE_USER:-1000}
      PGID: ${SERVICE_GROUP:-1000}
      UMASK: 022
    ports:
      - '172.17.0.1:6969:6969'
    volumes:
      - './volumes/config/whisparr:/config'
      - './volumes/data/media/adult:/data/adult'
      - './volumes/data/downloads:/data/downloads'
    labels:
      - 'traefik.enable=true'
      - 'cloudflare.enable=true'
      - 'traefik.docker.network=proxy'
      - 'cloudflare.service=http://arrstack-whisparr:6969'
      - 'cloudflare.hostname=arrstack.${CLOUDFLARE_ZONE_NAME:-}'
      - 'traefik.http.routers.arrstack-whisparr.entrypoints=http'
      - 'traefik.http.routers.arrstack-whisparr-secure.tls=true'
      - 'traefik.http.routers.arrstack-whisparr.rule=Host($(${BASE_HOST_NAME:-$HOSTNAME}))'
      - 'traefik.http.middlewares.arrstack-whisparr-https-redirect.redirectscheme.scheme=https'
      - 'traefik.http.routers.arrstack-whisparr.middlewares=arrstack-whisparr-https-redirect'
      - 'traefik.http.routers.arrstack-whisparr-secure.entrypoints=https'
      - 'traefik.http.routers.arrstack-whisparr-secure.rule=Host($(${BASE_HOST_NAME:-$HOSTNAME}))'
      - 'traefik.http.routers.arrstack-whisparr-secure.tls.certresolver=cloudflare'
      - 'traefik.http.routers.arrstack-whisparr-secure.service=arrstack-whisparr'
      - 'traefik.http.services.arrstack-whisparr.loadbalancer.server.port=6969'
    networks:
      - arrstack
      - proxy
      - cloudflare

  # Bazarr: A companion application to Sonarr and Radarr that manages and downloads subtitles.
  bazarr:
    image: ghcr.io/hotio/bazarr:latest
    container_name: arrstack-bazarr
    hostname: ${BASE_HOST_NAME:-$HOSTNAME}
    restart: always
    pull_policy: always
    logging: *default-logging
    environment:
      TZ: ${TZ:-America/New_York}
      CONTAINER_NAME: arrstack-bazarr
      HOSTNAME: ${BASE_HOST_NAME:-$HOSTNAME}
      PUID: ${SERVICE_USER:-1000}
      PGID: ${SERVICE_GROUP:-1000}
      UMASK: 022
    ports:
      - '172.17.0.1:6767:6767'
    volumes:
      - './volumes/config/bazarr:/config'
      - './volumes/data/media/tv:/data/tv'
      - './volumes/data/media/movies:/data/movies'
    labels:
      - 'traefik.enable=true'
      - 'cloudflare.enable=true'
      - 'traefik.docker.network=proxy'
      - 'cloudflare.service=http://arrstack-bazarr:6767'
      - 'cloudflare.hostname=arrstack.${CLOUDFLARE_ZONE_NAME:-}'
      - 'traefik.http.routers.arrstack-bazarr.entrypoints=http'
      - 'traefik.http.routers.arrstack-bazarr-secure.tls=true'
      - 'traefik.http.routers.arrstack-bazarr.rule=Host($(${BASE_HOST_NAME:-$HOSTNAME}))'
      - 'traefik.http.middlewares.arrstack-bazarr-https-redirect.redirectscheme.scheme=https'
      - 'traefik.http.routers.arrstack-bazarr.middlewares=arrstack-bazarr-https-redirect'
      - 'traefik.http.routers.arrstack-bazarr-secure.entrypoints=https'
      - 'traefik.http.routers.arrstack-bazarr-secure.rule=Host($(${BASE_HOST_NAME:-$HOSTNAME}))'
      - 'traefik.http.routers.arrstack-bazarr-secure.tls.certresolver=cloudflare'
      - 'traefik.http.routers.arrstack-bazarr-secure.service=arrstack-bazarr'
      - 'traefik.http.services.arrstack-bazarr.loadbalancer.server.port=6767'
    networks:
      - arrstack
      - proxy
      - cloudflare

  # Jackett: API Support for your favorite torrent trackers, translating searches into tracker-site-specific queries.
  jackett:
    image: ghcr.io/hotio/jackett:latest
    container_name: arrstack-jackett
    hostname: ${BASE_HOST_NAME:-$HOSTNAME}
    restart: always
    pull_policy: always
    logging: *default-logging
    environment:
      TZ: ${TZ:-America/New_York}
      CONTAINER_NAME: arrstack-jackett
      HOSTNAME: ${BASE_HOST_NAME:-$HOSTNAME}
      PUID: ${SERVICE_USER:-1000}
      PGID: ${SERVICE_GROUP:-1000}
      UMASK: 022
    ports:
      - '172.17.0.1:9117:9117'
    volumes:
      - './volumes/config/jackett:/config'
      - './volumes/data/downloads:/data/downloads'
    labels:
      - 'traefik.enable=true'
      - 'cloudflare.enable=true'
      - 'traefik.docker.network=proxy'
      - 'cloudflare.service=http://arrstack-jackett:9117'
      - 'cloudflare.hostname=arrstack.${CLOUDFLARE_ZONE_NAME:-}'
      - 'traefik.http.routers.arrstack-jackett.entrypoints=http'
      - 'traefik.http.routers.arrstack-jackett-secure.tls=true'
      - 'traefik.http.routers.arrstack-jackett.rule=Host($(${BASE_HOST_NAME:-$HOSTNAME}))'
      - 'traefik.http.middlewares.arrstack-jackett-https-redirect.redirectscheme.scheme=https'
      - 'traefik.http.routers.arrstack-jackett.middlewares=arrstack-jackett-https-redirect'
      - 'traefik.http.routers.arrstack-jackett-secure.entrypoints=https'
      - 'traefik.http.routers.arrstack-jackett-secure.rule=Host($(${BASE_HOST_NAME:-$HOSTNAME}))'
      - 'traefik.http.routers.arrstack-jackett-secure.tls.certresolver=cloudflare'
      - 'traefik.http.routers.arrstack-jackett-secure.service=arrstack-jackett'
      - 'traefik.http.services.arrstack-jackett.loadbalancer.server.port=9117'
    networks:
      - arrstack
      - proxy
      - cloudflare

  # Unpackerr: Extracts archives for various media server software like Sonarr, Radarr, Lidarr, etc.
  unpackerr:
    image: ghcr.io/hotio/unpackerr:latest
    container_name: arrstack-unpackerr
    hostname: ${BASE_HOST_NAME:-$HOSTNAME}
    restart: always
    pull_policy: always
    logging: *default-logging
    environment:
      TZ: ${TZ:-America/New_York}
      CONTAINER_NAME: arrstack-unpackerr
      PUID: ${SERVICE_USER:-1000}
      PGID: ${SERVICE_GROUP:-1000}
      UMASK: 022
    volumes:
      - './volumes/config/unpackerr:/config'
      - './volumes/data/downloads:/data/downloads'
    networks:
      - arrstack

  # Overseerr: A request management and media discovery tool for Plex. Integrates with Sonarr and Radarr.
  overseerr:
    image: ghcr.io/hotio/overseerr:latest
    container_name: arrstack-overseerr
    hostname: ${BASE_HOST_NAME:-$HOSTNAME}
    restart: always
    pull_policy: always
    logging: *default-logging
    environment:
      TZ: ${TZ:-America/New_York}
      CONTAINER_NAME: arrstack-overseerr
      HOSTNAME: ${BASE_HOST_NAME:-$HOSTNAME}
      PUID: ${SERVICE_USER:-1000}
      PGID: ${SERVICE_GROUP:-1000}
      UMASK: 022
    ports:
      - '172.17.0.1:5055:5055'
    volumes:
      - './volumes/config/overseerr:/config'
    labels:
      - 'traefik.enable=true'
      - 'cloudflare.enable=true'
      - 'traefik.docker.network=proxy'
      - 'cloudflare.service=http://arrstack-overseerr:5055'
      - 'cloudflare.hostname=arrstack.${CLOUDFLARE_ZONE_NAME:-}'
      - 'traefik.http.routers.arrstack-overseerr.entrypoints=http'
      - 'traefik.http.routers.arrstack-overseerr-secure.tls=true'
      - 'traefik.http.routers.arrstack-overseerr.rule=Host($(${BASE_HOST_NAME:-$HOSTNAME}))'
      - 'traefik.http.middlewares.arrstack-overseerr-https-redirect.redirectscheme.scheme=https'
      - 'traefik.http.routers.arrstack-overseerr.middlewares=arrstack-overseerr-https-redirect'
      - 'traefik.http.routers.arrstack-overseerr-secure.entrypoints=https'
      - 'traefik.http.routers.arrstack-overseerr-secure.rule=Host($(${BASE_HOST_NAME:-$HOSTNAME}))'
      - 'traefik.http.routers.arrstack-overseerr-secure.tls.certresolver=cloudflare'
      - 'traefik.http.routers.arrstack-overseerr-secure.service=arrstack-overseerr'
      - 'traefik.http.services.arrstack-overseerr.loadbalancer.server.port=5055'
    networks:
      - arrstack
      - proxy
      - cloudflare

  # Transmission: A fast, easy, and free BitTorrent client with a web interface.
  transmission:
    image: linuxserver/transmission:latest
    container_name: arrstack-transmission
    hostname: ${BASE_HOST_NAME:-$HOSTNAME}
    restart: always
    pull_policy: always
    logging: *default-logging
    environment:
      TZ: ${TZ:-America/New_York}
      CONTAINER_NAME: arrstack-transmission
      HOSTNAME: ${BASE_HOST_NAME:-$HOSTNAME}
      PUID: ${SERVICE_USER:-1000}
      PGID: ${SERVICE_GROUP:-1000}
      UMASK: 002
      USER: ${APP_ADMIN_USER:-admin}
      PASS: ${APP_ADMIN_PASS:-changeme_admin_password}
    ports:
      - '172.17.0.1:9091:9091'
      - '172.17.0.1:51413:51413'
      - '172.17.0.1:51413:51413/udp'
    volumes:
      - './volumes/config/transmission:/config'
      - './volumes/data/watch:/watch'
      - './volumes/data/downloads:/data/downloads'
    labels:
      - 'traefik.enable=true'
      - 'cloudflare.enable=true'
      - 'traefik.docker.network=proxy'
      - 'cloudflare.service=http://arrstack-transmission:9091'
      - 'cloudflare.hostname=arrstack.${CLOUDFLARE_ZONE_NAME:-}'
      - 'traefik.http.routers.arrstack-transmission.entrypoints=http'
      - 'traefik.http.routers.arrstack-transmission-secure.tls=true'
      - 'traefik.http.routers.arrstack-transmission.rule=Host($(${BASE_HOST_NAME:-$HOSTNAME}))'
      - 'traefik.http.middlewares.arrstack-transmission-https-redirect.redirectscheme.scheme=https'
      - 'traefik.http.routers.arrstack-transmission.middlewares=arrstack-transmission-https-redirect'
      - 'traefik.http.routers.arrstack-transmission-secure.entrypoints=https'
      - 'traefik.http.routers.arrstack-transmission-secure.rule=Host($(${BASE_HOST_NAME:-$HOSTNAME}))'
      - 'traefik.http.routers.arrstack-transmission-secure.tls.certresolver=cloudflare'
      - 'traefik.http.routers.arrstack-transmission-secure.service=arrstack-transmission'
      - 'traefik.http.services.arrstack-transmission.loadbalancer.server.port=9091'
    networks:
      - arrstack
      - proxy
      - cloudflare

  # MeTube: A web GUI for youtube-dl with playlist support. Allows you to download videos from YouTube and dozens of other sites.
  metube:
    image: alexta69/metube:latest
    container_name: arrstack-metube
    hostname: ${BASE_HOST_NAME:-$HOSTNAME}
    restart: always
    pull_policy: always
    logging: *default-logging
    environment:
      TZ: ${TZ:-America/New_York}
      CONTAINER_NAME: arrstack-metube
      HOSTNAME: ${BASE_HOST_NAME:-$HOSTNAME}
      PUID: ${SERVICE_USER:-1000}
      PGID: ${SERVICE_GROUP:-1000}
    ports:
      - '172.17.0.1:8081:8081'
    volumes:
      - './volumes/data/downloads:/downloads'
    labels:
      - 'traefik.enable=true'
      - 'cloudflare.enable=true'
      - 'traefik.docker.network=proxy'
      - 'cloudflare.service=http://arrstack-metube:8081'
      - 'cloudflare.hostname=arrstack.${CLOUDFLARE_ZONE_NAME:-}'
      - 'traefik.http.routers.arrstack-metube.entrypoints=http'
      - 'traefik.http.routers.arrstack-metube-secure.tls=true'
      - 'traefik.http.routers.arrstack-metube.rule=Host($(${BASE_HOST_NAME:-$HOSTNAME}))'
      - 'traefik.http.middlewares.arrstack-metube-https-redirect.redirectscheme.scheme=https'
      - 'traefik.http.routers.arrstack-metube.middlewares=arrstack-metube-https-redirect'
      - 'traefik.http.routers.arrstack-metube-secure.entrypoints=https'
      - 'traefik.http.routers.arrstack-metube-secure.rule=Host($(${BASE_HOST_NAME:-$HOSTNAME}))'
      - 'traefik.http.routers.arrstack-metube-secure.tls.certresolver=cloudflare'
      - 'traefik.http.routers.arrstack-metube-secure.service=arrstack-metube'
      - 'traefik.http.services.arrstack-metube.loadbalancer.server.port=8081'
    networks:
      - arrstack
      - proxy
      - cloudflare

  # Audiobookshelf: Self-hosted audiobook and podcast server with a modern interface for managing and listening to your audio collections.
  audiobookshelf:
    image: ghcr.io/advplyr/audiobookshelf:latest
    container_name: arrstack-audiobookshelf
    hostname: ${BASE_HOST_NAME:-$HOSTNAME}
    restart: always
    pull_policy: always
    logging: *default-logging
    environment:
      TZ: ${TZ:-America/New_York}
      CONTAINER_NAME: arrstack-audiobookshelf
      HOSTNAME: ${BASE_HOST_NAME:-$HOSTNAME}
      PUID: ${SERVICE_USER:-1000}
      PGID: ${SERVICE_GROUP:-1000}
    ports:
      - '172.17.0.1:13378:80'
    volumes:
      - './volumes/config/audiobookshelf:/config'
      - './volumes/data/media/podcasts:/podcasts'
      - './volumes/data/media/audiobooks:/audiobooks'
    labels:
      - 'traefik.enable=true'
      - 'cloudflare.enable=true'
      - 'traefik.docker.network=proxy'
      - 'cloudflare.service=http://arrstack-audiobookshelf:80'
      - 'cloudflare.hostname=arrstack.${CLOUDFLARE_ZONE_NAME:-}'
      - 'traefik.http.routers.arrstack-audiobookshelf.entrypoints=http'
      - 'traefik.http.routers.arrstack-audiobookshelf-secure.tls=true'
      - 'traefik.http.routers.arrstack-audiobookshelf.rule=Host($(${BASE_HOST_NAME:-$HOSTNAME}))'
      - 'traefik.http.middlewares.arrstack-audiobookshelf-https-redirect.redirectscheme.scheme=https'
      - 'traefik.http.routers.arrstack-audiobookshelf.middlewares=arrstack-audiobookshelf-https-redirect'
      - 'traefik.http.routers.arrstack-audiobookshelf-secure.entrypoints=https'
      - 'traefik.http.routers.arrstack-audiobookshelf-secure.rule=Host($(${BASE_HOST_NAME:-$HOSTNAME}))'
      - 'traefik.http.routers.arrstack-audiobookshelf-secure.tls.certresolver=cloudflare'
      - 'traefik.http.routers.arrstack-audiobookshelf-secure.service=arrstack-audiobookshelf'
      - 'traefik.http.services.arrstack-audiobookshelf.loadbalancer.server.port=80'
    networks:
      - arrstack
      - proxy
      - cloudflare

  # Homarr: A modern, feature-rich dashboard for your server. Integrates with Docker for container management, supports multiple users with advanced permissions, and provides a sleek interface for managing your self-hosted services.
  homarr:
    image: ghcr.io/homarr-labs/homarr:latest
    container_name: arrstack-homarr
    hostname: ${BASE_HOST_NAME:-$HOSTNAME}
    restart: always
    pull_policy: always
    logging: *default-logging
    volumes:
      - './volumes/config/homarr:/appdata'
      - '/var/run/docker.sock:/var/run/docker.sock'
    environment:
      TZ: ${TZ:-America/New_York}
      CONTAINER_NAME: arrstack-homarr
      HOSTNAME: ${BASE_HOST_NAME:-$HOSTNAME}
      SECRET_ENCRYPTION_KEY: ${ENCRYPTION_KEY:-changeme_encryption_key_min_32_chars}
    ports:
      - '172.17.0.1:7575:7575'
    labels:
      - 'traefik.enable=true'
      - 'cloudflare.enable=true'
      - 'traefik.docker.network=proxy'
      - 'cloudflare.service=http://arrstack-homarr:7575'
      - 'cloudflare.hostname=arrstack.${CLOUDFLARE_ZONE_NAME:-}'
      - 'traefik.http.routers.arrstack-homarr.entrypoints=http'
      - 'traefik.http.routers.arrstack-homarr-secure.tls=true'
      - 'traefik.http.routers.arrstack-homarr.rule=Host($(${BASE_HOST_NAME:-$HOSTNAME}))'
      - 'traefik.http.middlewares.arrstack-homarr-https-redirect.redirectscheme.scheme=https'
      - 'traefik.http.routers.arrstack-homarr.middlewares=arrstack-homarr-https-redirect'
      - 'traefik.http.routers.arrstack-homarr-secure.entrypoints=https'
      - 'traefik.http.routers.arrstack-homarr-secure.rule=Host($(${BASE_HOST_NAME:-$HOSTNAME}))'
      - 'traefik.http.routers.arrstack-homarr-secure.tls.certresolver=cloudflare'
      - 'traefik.http.routers.arrstack-homarr-secure.service=arrstack-homarr'
      - 'traefik.http.services.arrstack-homarr.loadbalancer.server.port=7575'
    networks:
      - arrstack
      - proxy
      - cloudflare

networks:
  arrstack:
    name: arrstack
    external: false
  proxy:
    external: true
  cloudflare:
    external: true
